platform :ios, '8.4'
use_frameworks!

link_with 'EVE', 'EVETests'

pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :branch => 'swift-2.0'
pod 'SnapKit', :git => 'https://github.com/SnapKit/SnapKit.git', :branch => 'swift-2.0'
pod 'MarqueeLabel'
